services:

  weather-postgres:
    container_name: ${POSTGRES_HOST}
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h ${POSTGRES_HOST}" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - services

  weather-api:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      weather-postgres:
        condition: service_healthy
    ports:
      - "${MAIN_API_PORT}:${MAIN_API_PORT}"
    networks:
      - services

volumes:
  postgres_data:

networks:
  services: